//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class picture
    {
        public int picture_id { get; set; }
        public int person_id { get; set; }
        public string caption { get; set; }
        public string relative_path { get; set; }
        public string time_info { get; set; }
        public string location { get; set; }
    
        public virtual person person { get; set; }
    }
}
